### ISSUE TITLE
A mistake in Chapter 17.5

### ISSUE THREAD

**Issue by Youguang** [rstudio/rmarkdown-cookbook#330]
There is a mistake in the second code sample in Chapter 17.5:

```
#' Custom Knit function for RStudio
#'
#' @export
knit_with_date <- function(input, ...) {
  rmarkdown::render(
    input,
    output_file = paste0(
        xfun::sans_ext(input), '-', Sys.Date(), '.',
        xfun::file_ext(input)
    ),
    envir = globalenv()
  )
}
```

For input file `example.Rmd` on 2019-07-29 this function will output `example-2019-07-29.Rmd`.
There is no need to specify the file_ext for rmarkdown::render(). That is:

```
#' Custom Knit function for RStudio
#'
#' @export
knit_with_date <- function(input, ...) {
  rmarkdown::render(
    input,
    output_file = paste0(
      xfun::sans_ext(input), "-", Sys.Date()
    ),
    envir = globalenv()
  )
}
```

And I am not very clear about where to put `knit: myPackage::knit_with_date`, it worked when I put it in the header of my Rmd, but it said `argument "input" is missing, with no default` when I put it in `_output.yml` as below:

```
knit: myPackage::knit_with_date

html_document:
    df_print: kable
    dev: "svg"
    fig_width: 10
    fig_height: 3.36
    number_sections: true
    toc: true
    toc_float:
        collapsed: false
```
